import React from 'react'
import { signIn } from '../auth'
import Image from 'next/image';

export const metadata = {
  title: "Login",
  description: "Generated by login",
}

function page() {
  async function log() {
    'use server'
    await signIn("google", { redirectTo: "/" });
  }

  return (
    <div className="min-h-screen flex items-center justify-center bg-gray-100 p-4">
      <div className="max-w-md w-full bg-white shadow-lg rounded-lg p-8">
        <h2 className="text-3xl font-bold text-center text-[#0A66C2] mb-2">Welcome Back</h2>
        <p className="text-center text-gray-600 mb-6">Sign in to your account</p>

        <form className="space-y-5">
          <div>
            <label htmlFor="email" className="block text-gray-700 font-medium">Email</label>
            <input
              type="email"
              id="email"
              className="mt-1 w-full px-4 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-[#0A66C2]"
              placeholder="you@example.com"
            />
          </div>

          <div>
            <label htmlFor="password" className="block text-gray-700 font-medium">Password</label>
            <input
              type="password"
              id="password"
              className="mt-1 w-full px-4 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-[#0A66C2]"
              placeholder="••••••••"
            />
          </div>

          <div className="flex items-center justify-between">
            <div className="flex items-center">
              <input
                type="checkbox"
                id="remember"
                className="h-4 w-4 text-[#0A66C2] focus:ring-[#0A66C2] border-gray-300 rounded"
              />
              <label htmlFor="remember" className="ml-2 block text-gray-900 text-sm">
                Remember me
              </label>
            </div>
            <div className="text-sm">
              <a href="#" className="text-[#0A66C2] hover:underline">
                Forgot password?
              </a>
            </div>
          </div>

          <button
            type="submit"
            className="w-full bg-[#0A66C2] text-white py-2 rounded-full font-semibold hover:bg-[#004182] transition duration-200"
          >
            Login
          </button>
        </form>

        <div className="my-6 border-t border-gray-200" />

        <form action={log}>
          <button
            type="submit"
            className="flex items-center justify-center gap-3 px-6 py-2 w-full bg-white border border-gray-300 rounded-full shadow-sm hover:shadow-md transition text-sm text-gray-700"
          >
            <Image
              src="https://www.svgrepo.com/show/475656/google-color.svg"
              alt="Google logo"
              className="w-5 h-5"
              width={100}
              height={100}
            />
            Sign in with Google
          </button>
        </form>

        <p className="mt-6 text-center text-gray-600 text-sm">
          Don t have an account?
          <a href="#" className="text-[#0A66C2] hover:underline font-medium ml-1">
            Sign up
          </a>
        </p>
      </div>
    </div>
  )
}

export default page
